pipeline{
    agent any
    environment{
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages{
        stage('git checkout'){
            steps{
                dir('vote'){
                    git branch: 'main', url: 'https://github.com/mukeshr-29/Voting-app-microServices.git'
                }
            }
        }
        stage('filesystem scan'){
            steps{
                dir('vote'){
                    sh 'trivy fs --format table -o trivyfs-votereport.html .'
                }
            }
        }
        stage('static code analysis'){
            steps{
                dir('vote'){
                    script{
                        withSonarQubeEnv('sonar-server'){
                            sh '''
                                $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=vote-service \
                                    -Dsonar.projectKey=vote-service
                            '''
                        }
                    }
                }
            }
        }
        stage('quality gate'){
            steps{
                dir('vote'){
                    script{
                        waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                    }
                }
            }
        }
        stage('docker image build and tag'){
            steps{
                dir('vote'){
                    sh 'docker build -t mukeshr29/vote-service .'
                }
            }
        }
        stage('docker image scanning'){
            steps{
                dir('vote'){
                    sh 'trivy image --format table -o trivyimg-votereport.html mukeshr29/vote-service'
                }
            }
        }
        stage('docker image push to repo'){
            steps{
                script{
                    withDockerRegistry(credentialsId: 'dockerhub', toolName: 'docker'){
                        sh 'docker push mukeshr29/vote-service'
                    }
                }
            }
        }
        stage('deploy to k8s'){
            steps{
                dir('vote'){
                    script{
                        withKubeConfig(caCertificate: '', clusterName: 'my-app', contextName: '', credentialsId: 'k8s', namespace: 'vote', restrictKubeConfigAccess: false, serverUrl: 'https://7AE0C0CA10BA163F2369F1970D91B954.gr7.us-east-1.eks.amazonaws.com'){
                            sh 'kubectl apply -f vote-deployment.yaml -f vote-service.yaml'
                        }
                    }
                }
            }
        }
    }
}